### ISSUE TITLE
Details for 2k17 Milestone

### ISSUE THREAD

**Issue by MythicAngel** [MythicAngel/Wordpress-Solutions#10]
# Sign-off for following plugins:
- [x] OAuth plugin with new bootstrap UI #13 
- [X] Facebook group post to wordpress posts
- [X] Sitemap support
- [x] Facebook album as wordpress post #11 
- [X] Emergency caching

# Beta version ready:
- [x] Theme: PALADIN-AC
- [x] Theme: BUETian.com 4.0 re-write #12 
- [x] Theme: BUETian.com 5.0 (responsive design)

**Comment by MythicAngel** [comment]
Completed all :-)
